-- Script para verificar y recrear tablas de Spring Session si es necesario
-- Ejecutar en la base de datos db_telito

USE db_telito;

-- Verificar si existen las tablas
SELECT 
    CASE 
        WHEN COUNT(*) = 2 THEN '✅ Las tablas de Spring Session existen'
        ELSE '❌ Faltan tablas de Spring Session'
    END AS estado
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'db_telito'
AND TABLE_NAME IN ('SPRING_SESSION', 'SPRING_SESSION_ATTRIBUTES');

-- Mostrar las tablas que existen
SELECT TABLE_NAME, CREATE_TIME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'db_telito'
AND TABLE_NAME LIKE 'SPRING_SESSION%';

-- Si no existen, crearlas
CREATE TABLE IF NOT EXISTS SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE UNIQUE INDEX IF NOT EXISTS SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE IF NOT EXISTS SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES LONGBLOB NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) 
        REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Limpiar sesiones expiradas antiguas
DELETE FROM SPRING_SESSION WHERE EXPIRY_TIME < UNIX_TIMESTAMP(NOW()) * 1000;

-- Mostrar sesiones activas
SELECT 
    COUNT(*) as sesiones_activas,
    PRINCIPAL_NAME,
    FROM_UNIXTIME(CREATION_TIME/1000) as fecha_creacion,
    FROM_UNIXTIME(LAST_ACCESS_TIME/1000) as ultimo_acceso,
    FROM_UNIXTIME(EXPIRY_TIME/1000) as fecha_expiracion
FROM SPRING_SESSION
WHERE EXPIRY_TIME > UNIX_TIMESTAMP(NOW()) * 1000
GROUP BY PRINCIPAL_NAME, CREATION_TIME, LAST_ACCESS_TIME, EXPIRY_TIME;

-- Verificación final
SELECT '✅ Script ejecutado correctamente. Spring Session está configurado.' AS resultado;
